// Generated by scripts/build-records.js. Do not edit by hand.
window.LIFE_LINE_RECORDS = [
  {
    "title": "2026/05/19",
    "date": "2026-05-19",
    "category": "记录",
    "summary": "0519测试",
    "href": "./records/2026/05/19/"
  },
  {
    "title": "测试",
    "date": "2026-05-17",
    "category": "记录",
    "summary": "fisrt test",
    "href": "./records/2026/05/17/"
  },
  {
    "title": "最近的状态",
    "date": "2026-04-03",
    "category": "生活",
    "summary": "压力有些大，先休息几天，恢复节奏。",
    "href": "./records/2026/04/03/"
  }
];
